### ISSUE TITLE
How to use with existing Next Images

### ISSUE THREAD

**Issue by wa1id** [lorenzodejong/next-sanity-image#49]
Currently getting `Image with src "/_next/static/media/logo.215ee7a5.png" is missing "loader" prop.`

How to make it compatible with already existing Next Images?

**Comment by yesid-lopez** [comment]
I'm having the same issue

**Comment by lorenzodejong** [comment]
I think i noticed some other people running into similar issues. Apparently this has to do with the custom loader setting in `next.config.js`: https://github.com/lorenzodejong/next-sanity-image/issues/51#issuecomment-1372494687

**Comment by lorenzodejong** [comment]
I'll make sure to update the documentation somewhere this week, closing for now. Feel free to re-open if this doesn't solve your issue.
