### ISSUE TITLE
Error on deploy, Conflic sanity-client

### ISSUE THREAD

**Issue by narr07** [lorenzodejong/next-sanity-image#59]
While resolving: next-sanity-image@6.0.0
--
05:15:03.422 | npm ERR! Found: @sanity/client@6.1.0
05:15:03.423 | npm ERR! node_modules/@sanity/client
05:15:03.423 | npm ERR!   @sanity/client@"^6.1.0" from the root project
05:15:03.423 | npm ERR!   @sanity/client@"^6.0.0" from @sanity/preview-kit@1.5.2
05:15:03.423 | npm ERR!   node_modules/@sanity/preview-kit
05:15:03.424 | npm ERR!     @sanity/preview-kit@"^1.5.0" from next-sanity@4.3.2
05:15:03.424 | npm ERR!     node_modules/next-sanity
05:15:03.424 | npm ERR!       next-sanity@"^4.3.2" from the root project
05:15:03.424 | npm ERR!   1 more (next-sanity)
05:15:03.424 | npm ERR!
05:15:03.424 | npm ERR! Could not resolve dependency:
05:15:03.424 | npm ERR! peer @sanity/client@"^5.0.0" from next-sanity-image@6.0.0
05:15:03.425 | npm ERR! node_modules/next-sanity-image
05:15:03.425 | npm ERR!   next-sanity-image@"^6.0.0" from the root project
05:15:03.425 | npm ERR!
05:15:03.426 | npm ERR! Conflicting peer dependency: @sanity/client@5.4.2
05:15:03.426 | npm ERR! node_modules/@sanity/client
05:15:03.426 | npm ERR!   peer @sanity/client@"^5.0.0" from next-sanity-image@6.0.0
05:15:03.426 | npm ERR!   node_modules/next-sanity-image
05:15:03.426 | npm ERR!     next-sanity-image@"^6.0.0" from the root project

**Comment by roelvan** [comment]
You can use this fork untill the pull request gets accepted: `npm i next-sanity-image-fork`

**Comment by lorenzodejong** [comment]
Sorry for the late reply. Version 6.1.0 is now released with support for `@sanity/client` version `^6.0.0`.
