### ISSUE TITLE
Spike in Sanity Bandwidth

### ISSUE THREAD

**Issue by khalilp5** [lorenzodejong/next-sanity-image#60]
Has anyone seen a spike in sanity bandwidth after installing and implementing this package. I have installed this package last year around September and seen significant upward trend in bandwidth of Sanity. 

Just want to understand if this package is causing this issue.

**Comment by lorenzodejong** [comment]
This package introduces responsive images, which means that images with different sizes are served corresponding to the user's screen size.

This package does nothing more apart from setting the properties for the 'next/image' component. This package does not perform any data calls to the Sanity API.

Anything that's true for the (browser) responsive image specification is also true for the use of this library: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images.

**Comment by khalilp5** [comment]
I mean does the initialisation of builder as seen in the source code incur bandwidth? I see the builder getting initialised in the hook call.

**Comment by lorenzodejong** [comment]
Nope, as i mentioned this library does not trigger any data calls. As you can see in the source code there's no async code, promises or even useEffect hooks.

Check your devtools network tab for the data calls that are being made. From there you can gain more insight in which images are being loaded. You'll notice that when you resize your screen network requests will trigger for the different image sizes.

**Comment by kelenakamura** [comment]
> I mean does the initialisation of builder as seen in the source code incur bandwidth? I see the builder getting initialised in the hook call.

@khalilp5 did you ever find out what was causing the bandwidth spike? we've seen it as well.

**Comment by garrettboatman** [comment]
For @kelenakamura and anybody who finds this in the future: For us, had to do with `useNextSanityImage` hook needing a client component and running on each render as opposed to at build time. We reverted back to using [sanity-io/image-url](https://github.com/sanity-io/image-url) in a custom wrapper for next/image.

This works for us:
```typescript
// /utils/sanity/client.ts

import { createClient } from '@sanity/client';
import imageUrlBuilder from '@sanity/image-url';
import { SanityImageSource } from '@sanity/image-url/lib/types/types';

const projectId = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID;
const dataset = process.env.NEXT_PUBLIC_SANITY_DATASET;
const apiVersion = process.env.NEXT_PUBLIC_SANITY_API_VERSION || '2023-05-03';

const client = createClient({
  projectId,
  dataset,
  apiVersion,
  useCdn: true,
});

const builder = imageUrlBuilder(client);

export function urlForImage(source: SanityImageSource) {
  return builder.image(source);
}

export default client;

```
```typescript
// /src/components/SanityImage.tsx

import Image, { ImageProps } from 'next/image';
import { ReactElement } from 'react';

import { urlForImage } from '@/utils/sanity/client';

const getDimensionsFromRef = (
  ref: string | undefined,
): { width: number; height: number } | null => {
  if (!ref) return null;

  const match = ref.match(/-(\d+)x(\d+)-/);
  if (match && match[1] && match[2]) {
    return {
      width: parseInt(match[1], 10),
      height: parseInt(match[2], 10),
    };
  }
  return null;
};

interface SanityImageProps
  extends Omit<ImageProps, 'src' | 'width' | 'height'> {
  image: any;
  maxWidth?: number;
}

const SanityImage = ({
  image,
  maxWidth,
  alt,
  ...props
}: SanityImageProps): ReactElement | null => {
  if (!image?.asset?._ref) {
    return null;
  }

  const dimensions = getDimensionsFromRef(image.asset._ref);

  if (!dimensions) {
    return null;
  }

  const { width, height } = dimensions;
  const imageAlt = alt ?? image?.alt ?? 'Image';

  let imageWidth = width;
  let imageHeight = height;

  if (maxWidth && width > maxWidth) {
    const aspectRatio = width / height;
    imageWidth = maxWidth;
    imageHeight = Math.round(maxWidth / aspectRatio);
  }

  return (
    <Image
      src={urlForImage(image).width(imageWidth).height(imageHeight).url()}
      alt={imageAlt}
      width={imageWidth}
      height={imageHeight}
      {...props}
    />
  );
};

export default SanityImage;
```
