### ISSUE TITLE
Next 14 breaks with next-sanity-image when deployed to Vercel

### ISSUE THREAD

**Issue by henrybabbage** [lorenzodejong/next-sanity-image#63]
Hello,

After updating to NextJS 14, my project in which next-sanity-image is a dependency broke when deploying to Vercel.

Error log below:

<img width="1200" alt="next-sanity-image-error" src="https://github.com/lorenzodejong/next-sanity-image/assets/84812889/5f92d713-4353-41cb-8be1-6b54edf4920d">

Currently working around this by setting `"npm install --legacy-peer-deps"` in the Vercel Build & Development Settings for the project.

**Comment by lorenzodejong** [comment]
Version `6.1.1` has just been released which supports `next@^14.0.0` from the peerDependencies: https://github.com/lorenzodejong/next-sanity-image/releases/tag/v6.1.1.
