### ISSUE TITLE
Does this support next-sanity 7?

### ISSUE THREAD

**Issue by oorestisime** [lorenzodejong/next-sanity-image#65]
Peer deps saying no.

is it on the plans maybe?

Thanks

**Comment by andershagbard** [comment]
I am using this with version 7. Works fine.

**Comment by lorenzodejong** [comment]
Which peer dependencies specifically are not matched? Just took a quick peek into [next-sanity's package.json](https://github.com/sanity-io/next-sanity/blob/main/package.json) and it doesn't seem like there's incompatibilities.
